title: Positive Peace Edits
description: ""
url: "https://yourusername.github.io"
baseurl: "" # if not using a subdirectory

theme: null # Required to override default theme
remote_theme: mmistakes/so-simple-theme

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# So Simple settings
author:
  name: 
  location: 
  email: 

# social links, nav, etc.
