title: Positive Peace
description: ""
url: "https://yourusername.github.io"
baseurl: "" # if not using a subdirectory

navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Archive
    url: /posts/

theme: null # Required to override default theme
remote_theme: mmistakes/so-simple-theme

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# So Simple settings
author:
  name: 
  location: 
  email: 

# social links, nav, etc.
