title: Positive Peace
description: Welcome 2
baseurl: ""
url: ""

# Theme - use remote_theme for GitHub Pages
remote_theme: mmistakes/so-simple-theme

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme
